### ISSUE TITLE
Задание 1

### ISSUE THREAD

**Issue by readysloth** [Gr0v4222/ArchVs#1]
![image](https://user-images.githubusercontent.com/28711485/97474070-bf2cc500-195c-11eb-94b5-2fe501c8879a.png)

Почему вы уверены, что аргументы в `fun1` передаются через `ecx`?
Как доп. вопрос: **что такое соглашение о вызовах и зачем оно нужно**
Как доп. вопрос: **в каком порядке передаются аргументы в функции**
https://github.com/Gr0v4222/ArchVs/blob/8bb0590e3a73927766c9ffe0913c544dd3967912/Lab3/L3Z1/fun1.S#L2-L3

Зачем это происходит? (тут комментов нет, но в отчете вы перепутали лево и право)
https://github.com/Gr0v4222/ArchVs/blob/8bb0590e3a73927766c9ffe0913c544dd3967912/Lab3/L3Z1/fun1.S#L4-L5

Это точно то задание, что вы указали в отчете?))
https://github.com/Gr0v4222/ArchVs/blob/8bb0590e3a73927766c9ffe0913c544dd3967912/Lab3/L3Z1/fun1.S#L6

Вы подняли мне настроение этим скриншотом :) 
Как доп. вопрос: **скажите мне, что с ним не так**
![image](https://user-images.githubusercontent.com/28711485/97474716-732e5000-195d-11eb-997e-4fa70d8ebd88.png)

**Comment by yulia9112** [comment]
что такое соглашение о вызовах и зачем оно нужно:  способы передачи результатов вычислений, выполненных подпрограммами, в точку вызова, то есть точка вызова у нас fun1(i).  
в mov присваивание ecx в eax.
а ещё похоже у нас ошибки, потому что нет умножение на -1 каждого аргумента и каждое число по циклу имеет одинаковое ассемблерное значение.

**Comment by yulia9112** [comment]
Похоже мы местами перепутали в mov
должно быть mov %eax, %ecx

**Comment by yulia9112** [comment]
хотя можно и через %esp достать(из стека)
.global _fun1
_fun1:
mov -4(%esp), %eax
shr $2, %eax  // ответ на второй вопрос:  это умножение и деление на 4( путем сдвига влево и вправо)
shl $2, %eax
imul $-1, %eax
ret

**Comment by yulia9112** [comment]
![Screenshot_2020-11-02-18-28](https://user-images.githubusercontent.com/60868878/97887173-992b6a00-1d3a-11eb-8287-8a70bcb1b6dd.jpg)

**Comment by yulia9112** [comment]
либо вот поменять местами где у нас ecx регистр счётчика 
.global _fun1
_fun1:
mov %eax, %ecx
shr $2, %eax 
shl $2, %eax
imul $-1, %eax
ret

вывод такой же как и выше кинула
