### ISSUE TITLE
Задание 3

### ISSUE THREAD

**Issue by readysloth** [Gr0v4222/ArchVs#2]
![image](https://user-images.githubusercontent.com/28711485/97476729-d1f4c900-195f-11eb-9046-4ae1cbc2d64a.png)
![image](https://user-images.githubusercontent.com/28711485/97476790-e46f0280-195f-11eb-8b65-8b5301bd6e16.png)

**Comment by yulia9112** [comment]
![image](https://user-images.githubusercontent.com/60868878/97890629-d09c1580-1d3e-11eb-8c3c-98335c38476c.png)

**Comment by yulia9112** [comment]
![Uploading image.png…]()

**Comment by yulia9112** [comment]
![image](https://user-images.githubusercontent.com/60868878/97890723-ef021100-1d3e-11eb-9ee2-108f6e552d5b.png)

**Comment by yulia9112** [comment]
поменяли местами push b push a
