### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by readysloth** [Gr0v4222/ArchVs#3]
+ Чем опасно переполнение стека?
+ Зачем нужны ассемблерные модули, если пишем на высокоуровневых языках? (1-2 примера)
+ Через какие этапы проходит исходный код, чтобы превратиться в исполняемый файл?
   + На каком из них будут использованы ассемблерные модули?

Можете прикреплять картинки/ссылаться на статьи из интернета, чтобы было наглядно :)

**Comment by yulia9112** [comment]
1. При переполнении стека больше не смогут вызываться пользовательские функции, поэтому операционная система забирает управление, очищает стек и завершает программу

**Comment by yulia9112** [comment]
2. Ассемблерная вставка даёт оптимизацию - возможность написать что-то на низком уровне, чтобы значительно упростить данную часть программы, убрав огромное количество ненужного кода, который бы появился при переводе компилятором кода с языка высокого уровня на более низкий и ещё даёт прямой доступ к системе, код на ассемблере позволяет выполнить прямое обращение к ядру операционной системы, что упростит программу и сделает ее быстрее

**Comment by yulia9112** [comment]
3.  **1) Препроцессинг
     2) Компиляция
     3) Ассемблирование**
           Ассемблер преобразовывает ассемблерный код в машинный код, сохраняя его в объектном файле.
           **Объектный файл** — это созданный ассемблером промежуточный файл, хранящий кусок машинного кода. Этот 
     кусок машинного кода, который еще не был связан вместе с другими кусками машинного кода в конечную 
     выполняемую программу, называется объектным кодом.
     **4) Компоновка(линкер)
     5) Загрузка**
