### ISSUE TITLE
Вопросы к лабораторной №4 

### ISSUE THREAD

**Issue by readysloth** [Gr0v4222/ArchVs#4]
+ Какой ограничитель на расположение операнда стоит написать, чтобы дать компилятору наибольшую свободу в применении оптимизаций?
+ Есть несколько способов поставить программную точку останова в C/C++ коде (аналогичную `pdb.set_trace()` в питоне). Как это будет записано с помощью ассемблерной вставки?
+ Каким образом (назовите хотя бы один) можно принудительно выставить флаги процессора в те значения, которые вы хотите

**Comment by yulia9112** [comment]
3. Можно делать условные переходы(т.к. они реагируют на изменения флагов) после любой команды, изменяющей флаги, например dec. Она меняет флаги, но не трогает CF. 

```
  mov eax, 10;
@DecEax:
  dec eax;
  jnz @DecEax;
```

После выполнения этой цепочки команд eax примет значение 0. Команда dec в этом примере устанавливает флаги.

Источник: http://osinavi.ru/asm/5.html

**Comment by Gr0v4222** [comment]
1.
"+m,r" (output) : "ir,irm" (input)
Это описывает все доступные альтернативы компилятору, позволяя ему выбрать наиболее эффективный для текущих условий.
Источник: https://gcc.gnu.org/onlinedocs/gcc/Multi-Alternative.html

**Comment by wowmeow** [comment]
2.  __asm { int 3;}  
     __asm { db 0xCC;}
