### ISSUE TITLE
Лабораторная 5 Вопросы

### ISSUE THREAD

**Issue by readysloth** [Gr0v4222/ArchVs#5]
+ Что такое выравнивание памяти и какой операцией оно выполняется? (это логическая операция)
+ Что такое *flexible array member* в структурах C и для чего это нужно?

**Comment by wowmeow** [comment]
**Flexible array member** is a feature that is introduced by C99 is flexible array member. This feature enables the user to create an empty array in a structure, the size of the empty array can be changed at runtime as per the user requirements. This empty array should be declared as the last member of the structure and the structure must contain at least one more named member.

When a structure has a flexible array member, the entire structure becomes an incomplete type. Basically, an incomplete type structure is a type that has a lack of information about its members.

To understand the above question we need to take an example. Suppose there is an application that has a structure that contains the character array whose size is 30 bytes. This array is used to store the address of the users. Here, problem is that when you create a variable using this structure then every time compiler reserve 30 bytes for the array.

If the length of the user address is less than 30 bytes, the extra remaining memory of array would be a waste. In some scenarios, it can be possible the length of the address could be greater than 30 bytes, this type of situation creates a problem and might be you will get the boundary issues.

Источник: https://aticleworld.com/flexible-array-member/

**Comment by yulia9112** [comment]
Выравнивание данных влияет на скорость выполнения ваших программ и на то, будут ли они вообще работать.
Считывание данных производится блоками по 2, 4, 8, 16 или даже 32 байта.
Если не выравнивать данные, то:
1. Приложение будет работать медленнее.
2. Приложение может "зависнуть".
3. Операционная система может внезапно аварийно завершиться.
4. Приложение будет работать непредсказуемо, что в итоге может привести к порче ваших данных.

Каждый процессор имеет ограниченное количество транзисторов, которое может быть в нем использовано. Добавление поддержки доступа к невыровненным данным вынуждает инженеров уменьшать количество транзисторов, предназначенных для обеспечения работы остальных подсистем процессора, что может сделать невозможным добавление каких-либо дополнительных возможностей в процессор или несколько снизить скорость его работы.

Источник: http://konishchevdmitry.blogspot.com/2010/01/blog-post.html

Многие архитектуры вовсе не позволяют читать такие слова, и для того, чтобы прочитать вот такое слово
![image](https://user-images.githubusercontent.com/60868878/102190241-d43bc400-3ec8-11eb-860d-2ccd02b363fd.png)
приходится читать машинные слова по адресу 0 и 4
![image](https://user-images.githubusercontent.com/60868878/102190271-def65900-3ec8-11eb-830d-0b7b9c607435.png)
выбирать из них нужные байты, перетасовывать и собирать «вручную» в нужное машинное слово! Это сложная и дорогостоящая операция.
Пример: для такой структуры:
![image](https://user-images.githubusercontent.com/60868878/102190095-9dfe4480-3ec8-11eb-84ae-864db77e0e38.png)
Поэтому компиляторы языка программирования C++ проводят такую оптимизацию: между полями структуры вставляются незначащие байты для того, чтобы у всех полей было хорошее выравнивание.
Бóльшая структура означает бóльший расход памяти и бóльшие затраты на копирование, чтение этой структуры и тому подобное. Таким образом, переставив поля структуры, мы можем сэкономить.

Источник: https://ru.stackoverflow.com/questions/435726/%D0%92%D1%8B%D1%80%D0%B0%D0%B2%D0%BD%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85
